#+TITLE: HA's VulnHub | DarkHole2 Config
#+AUTHOR: Hussien Almalki (HA)
#+DESCRIPTION: HA's personal VulnHub DarkHole2 config.
#+STARTUP: showeverything
#+OPTIONS: toc:2
#+EMAIL: r00t@hotmail.sg
#+LANGUAGE:  en
#+OPTIONS:   H:3 num:t   toc:3 \n:nil @:t ::t |:t ^:nil -:t f:t *:t <:nil
#+OPTIONS:   TeX:t LaTeX:nil skip:nil d:nil todo:t pri:nil tags:not-in-toc
#+OPTIONS:   author:t creator:t timestamp:t email:t
#+KEYWORDS:  Emacs Org-Mode Template
#+OPTIONS: toc:2

* TABLE OF CONTENTS :toc:
- [[#executive-summary][Executive Summary]]
  - [[#scope-of-work][Scope of work]]
  - [[#project-objectives][Project Objectives]]
  - [[#assumption][Assumption]]
  - [[#timeline][Timeline]]
  - [[#summary-of-findings][Summary of Findings]]
- [[#methodology][Methodology]]
  - [[#planning][Planning]]
  - [[#exploitation][Exploitation]]
  - [[#reporting][Reporting]]
- [[#detail-findings][Detail findings]]
  - [[#information-gathering][Information Gathering]]
  - [[#enumeration][Enumeration]]
  - [[#gaining-access][Gaining Access]]
  - [[#privilege-escalation][Privilege Escalation]]
- [[#conclusion][Conclusion]]
  - [[#recommendations][Recommendations]]
  - [[#risk-rating][Risk Rating]]
- [[#appendix-a-vulnerability-detail-and-mitigation][Appendix A: Vulnerability Detail and Mitigation]]
- [[#appendix-b-about-offensive-security][Appendix B: About Offensive Security]]

* Executive Summary
This document details the security assessment (external penetration testing) of VulnHub | DarkHole2. The purpose of the assessment was to provide a review of the security posture of VulnHub | darkHole2 Internet infrastructure, as well, as to identify potential weaknesses in its Internet infrastructure.


** Scope of work
This security assessment covers the remote penetration testing of one accessible server hosted on 192.168.0.11 addresses. The assessment was carried out from a black box perspective, with the only supplied information being the tested servers’ IP addresses. No other information was assumed at the start of the assessment.

** Project Objectives
This security assessment is carried out to gauge the security posture of VulnHub DarkHole2 Internet-facing hosts. The result of the assessment is then analyzed for vulnerabilities. Given the limited time that is given to perform the assessment, only immediately exploitable services have been tested. The vulnerabilities are assigned a risk rating based on threat, vulnerability, and impact.

** Assumption
While writing the report, we assume that both IP addresses are considered to be public IP addresses, NDA and rules of engagement have been signed, and based on the information gathering phase the company name is VunlHUB

** Timeline
The timeline of the test is as below:

| Penetration Testing | Start Date/time | End date/ Time |
|---------------------+-----------------+----------------|
| Pen Test 1          | mm/dd/yyyy      | mm/dd/yyyy     |


** Summary of Findings

* Methodology
** Planning
** Exploitation
** Reporting

* Detail findings
** Information Gathering
*Nmap* is free and open source software used for scanning and auditing the network. We are now initiating Nmap to advance in this process.

#+begin_src python
# Nmap 7.94 scan initiated Fri Feb 23 17:13:38 2024 as: nmap -sCV -p22,80 -oN targeted 192.168.0.11
Nmap scan report for 192.168.0.11
Host is up (0.00021s latency).

PORT   STATE SERVICE VERSION
22/tcp open  ssh     OpenSSH 8.2p1 Ubuntu 4ubuntu0.3 (Ubuntu Linux; protocol 2.0)
| ssh-hostkey: 
|   3072 57:b1:f5:64:28:98:91:51:6d:70:76:6e:a5:52:43:5d (RSA)
|   256 cc:64:fd:7c:d8:5e:48:8a:28:98:91:b9:e4:1e:6d:a8 (ECDSA)
|_  256 9e:77:08:a4:52:9f:33:8d:96:19:ba:75:71:27:bd:60 (ED25519)
80/tcp open  http    Apache httpd 2.4.41 ((Ubuntu))
| http-git: 
|   192.168.0.11:80/.git/
|     Git repository found!
|     Repository description: Unnamed repository; edit this file 'description' to name the...
|_    Last commit message: i changed login.php file for more secure 
|_http-server-header: Apache/2.4.41 (Ubuntu)
| http-cookie-flags: 
|   /: 
|     PHPSESSID: 
|_      httponly flag not set
|_http-title: DarkHole V2
MAC Address: 00:0C:29:5D:99:BA (VMware)
Service Info: OS: Linux; CPE: cpe:/o:linux:linux_kernel

Service detection performed. Please report any incorrect results at https://nmap.org/submit/ .
# Nmap done at Fri Feb 23 17:13:44 2024 -- 1 IP address (1 host up) scanned in 6.62 seconds
#+end_src

|   IP address | System Type | OS information       | Port | Protocal | Service Name |
| 192.168.0.11 | Server      | Apache/2.4.41 Ubuntu |   22 | TCP      | SSH          |
|              |             |                      |   80 | TCP      | http         |

** Enumeration
Enumeration: Using active and/or passive information gathering techniques, one can have a preliminary overview of the target system/network. Moving further, enumeration allows us to know what the exact services running on the target system (including types and versions) are and other information such as users, shares, and DNS entries. Enumeration prepares a clearer blueprint of the target we are trying to penetrate.

** Gaining Access
Gaining Access: Based on the target blueprint that we obtained from the information gathering and enumeration phase, it's now time to exploit the vulnerabilities in the target system and gain access. Gaining access to this target system involves exploiting one or many of the vulnerabilities found during earlier stages and possibly bypassing the security controls deployed in the target system (such as antivirus, firewall, IDS, and IPS).

** Privilege Escalation
Privilege Escalation: Quite often, exploiting a vulnerability on the target gives limited access to the system. However, we would want complete root/administrator level access into the target in order to gain most out of our exercise. This can be achieved using various techniques to escalate privileges of the existing user. Once successful, we can have full control over the system with highest privileges and can possibly infiltrate deeper into the target.


* Conclusion
** Recommendations
** Risk Rating

* Appendix A: Vulnerability Detail and Mitigation
* Appendix B: About Offensive Security
